spring:
    application:
        name: jambox-backend
    data:
        mongodb:
            port: 27017     # Standard MongoDB Port
            database:  ${DATABASE_NAME}
            # Für URI-basierte Verbindung:
            uri: ${DATABASE_URL}
            password: ${DATABASE_PASSWORD}
            username: ${DATABASE_USERNAME}
            authentication-database: ${DATABASE_AUTHENTICATION_DATABASE}
    security:
        oauth2:
            client:
                registration:
                    spotify:
                        client-id: ${SPOTIFY_CLIENT_ID}
                        client-secret: ${SPOTIFY_CLIENT_SECRET}
                        authorization-grant-type: authorization_code
                        redirect-uri: "${HOSTNAME}/login/oauth2/code/spotify"
                        scope: user-read-email
                        client-name: Spotify
                provider:
                    spotify:
                        authorization-uri: https://accounts.spotify.com/authorize
                        token-uri: https://accounts.spotify.com/api/token
                        user-info-uri: https://api.spotify.com/v1/me
                        user-name-attribute: id


jambox:
    oauth2-login-success-redirect: "http://127.0.0.1:4200/admin/dashboard"
    auth:
        authorized-emails:
            - ${SPOTIFY_EMAIL_ADDRESS}
    spotify:
        email-address: ${SPOTIFY_EMAIL_ADDRESS}
        callback-url: ${SPOTIFY_CALLBACK_URL}