spring:
    application:
        name: jambox-backend
    data:
        mongodb:
            port: 27017     # Standard MongoDB Port
            database: jambox # Ihr Datenbankname
            # Für URI-basierte Verbindung:
            uri: mongodb://
            password:
            username:
            authentication-database:

jambox:
    needsApproval: false
    #removeDupplicate: false
    #blacklist: false
    #whitelist: false
    spotify:
        client-id:
        client-secret:
        email-address:
        callback-url: "http://127.0.0.1:8080/spotify/callback" #Just Change the URL not the path